### ISSUE TITLE
Support namespace for stack installations

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane-cli#31]
Currently, `kubectl crossplane stack install` works for `default` and only `default` namespace. People who need to deploy the stack into a different namespace have to go with `kubectl crossplane stack install ... | kubectl -n myns -f -`.

It'd be good if crossplane cli supported namespaces natively.

**Comment by displague** [comment]
Closed by https://github.com/crossplaneio/crossplane-cli/pull/27
