### ISSUE TITLE
Publish new release of crossplane-cli

### ISSUE THREAD

**Issue by unladenSwallow** [crossplane/crossplane-cli#39]
The current deployed version of crossplane-cli:
```curl -sL https://raw.githubusercontent.com/crossplaneio/crossplane-cli/master/bootstrap.sh | bash```

does not include needed info such as namespace when installing a stack. Therefore, installing stacks via the command line does not work on this version. 

In order for stack installs to work with specifying a namespace, we need to update to release a new version that has all the functionality currently in master.

**Comment by negz** [comment]
If I follow correctly it sounds like we just need to cut a Github release to get this working as expected, right @unladenSwallow? @suskin @turkenh are we safe to do so?

**Comment by jbw976** [comment]
@suskin can you please publish a new release of crossplane-cli with the latest in master, unless you know of any reason to prevent us from doing that? thanks!

**Comment by suskin** [comment]
Yeah, definitely!

**Comment by suskin** [comment]
I've taken a closer look - the version can be specified by using the `RELEASE` environment variable when running the script:

```
curl -sL https://raw.githubusercontent.com/crossplaneio/crossplane-cli/master/bootstrap.sh | RELEASE=master bash
```

That may help with getting around the issue, or similar issues in the future.

I'm still going to release a new version though so that the default behavior picks up the new stuff : )

**Comment by suskin** [comment]
I've published a [v0.3.0 release](https://github.com/crossplaneio/crossplane-cli/releases/tag/v0.3.0)! Would you mind trying again @unladenSwallow ?

**Comment by unladenSwallow** [comment]
I will run through the process again this afternoon. Thanks all!

**Comment by unladenSwallow** [comment]
LGTM, thanks again :)

**Comment by suskin** [comment]
Awesome! Closing this then. Thanks @unladenSwallow !!
