### ISSUE TITLE
Build and publish: simplified CLI UX

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane-cli#44]
### What seems to be the problem
To build and publish a stack the following steps are required:

1. Run the following commands:
```
$ git clone git@github.com:crossplaneio/stack-minimal-gcp.git

$ cd stack-minimal-gcp

$ kubectl crossplane stack build

$ docker tag crossplane/stack-minimal-gcp crossplane/stack-minimal-gcp:v0.2.2

$ docker login registry.dev
Username: phil@prasek.org
Password:

$ kubectl crossplane stack publish registry.dev/crossplane/stack-minimal-gcp
```

### What could we do to help?

Support a cleaner build and publish CLI UX that does all the steps above:
```bash
VERSION=0.0.1
kubectl crossplane registry login registry.dev
kubectl crossplane stack build registry.dev/crossplane/stack-minimal-gcp:${VERSION}
kubectl crossplane stack publish registry.dev/crossplane/stack-minimal-gcp:${VERSION}
```

**Comment by connorchan** [comment]
The UI work for this was completed as part of: https://github.com/upbound/upbound-frontend/pull/1350

**Comment by displague** [comment]
@prasek Is it implied that this step would no longer be needed?  Or does this change in the instructions suggest that these two steps are obvious or outside the scope of `kubectl crossplane stack build` instructions?

```
$ git clone git@github.com:crossplaneio/stack-minimal-gcp.git
$ cd stack-minimal-gcp
```

Is the suggestion here that `kubectl crossplane stack build registry.dev/crossplane/stack-minimal-gcp:${VERSION}` would `git clone` into the current directory (creating a `stack-minimal-gcp:$version` sub-directory)?

Or is the suggestion and implication that the `build` command is run from the `stack-minimal-gcp` directory, already cloned, and the added `registry.dev/crossplane/stack-minimal-gcp:${VERSION}` build parameter simply (and optionally) informs the cli  to `docker tag` the resultant image following a successful build?

**Comment by prasek** [comment]
@displague The latter, that `git clone` and `cd` have already been done.

**Comment by displague** [comment]
It looks like the build tag was already supported with the right incantation:

```
kubectl crossplane stack build STACK_IMG=registry.foo/repo/image:tag
```

Changing this to support `kubectl crossplane stack build registry.foo/repo/image:tag` will mean making the `build` command (which is essentially an alias to `make build $*` lose the `$*` ability (the ability to pass arbitrary `make` arguments).

I also noticed that `kubectl crossplane stack publish registry.dev/crossplane/stack-minimal-gcp:${VERSION}` (with a tag) is already supported.

**Comment by displague** [comment]
I don't mind the symmetry between `build` and `publish` over the convenience of a `make build $*` alias.  `make` is still there (with less characters) if you need to send arbitrary commands.

**Comment by suskin** [comment]
I agree - we were mostly using the convenience for development and testing anyway, so it seems like it probably isn't necessary if it's standing in the way of user experience.
